// Ue01/BookShop/src/app/components/book-details/book-details.component.ts
import { Component, EventEmitter, Input, OnDestroy, OnInit, Output } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { Book } from 'src/app/models/book';
import { BookStoreService } from 'src/app/services/book-store.service';

@Component({
  selector: 'wea5-book-details',
  templateUrl: './book-details.component.html',
  styleUrls: ['./book-details.component.css']
})
export class BookDetailsComponent implements OnInit, OnDestroy {
  @Input() book: Book = new Book();
  
  private sub: Subscription;

  constructor(
    private route: ActivatedRoute,
    bookStoreService: BookStoreService,
    private router: Router) {
    this.sub = this.route.params.subscribe(params => {
      let id = params['id'];
      this.book = bookStoreService.getBookById(id);
      });
   }
  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  ngOnInit(): void {
  }

  showBookList() {
    this.router.navigateByUrl("/books");
  }
}

<div class="ui grid">
    <div class="four wide column">
        <img class="ui large image">
    </div>
    <div class="eight wide column">
        <h1 class="ui header">{{book?.title}}</h1>
        <h3 class="ui header">{{book?.author}}</h3>
        <div class="ui divider"></div>
        <div class="ui grid">
            <div class="four wide column">
                <h4 class="ui header">Preis</h4>
                {{book?.price}}
            </div>
            <div class="four wide column">
                <h4 class="ui header">Erschienen</h4>
                {{book?.year}}
            </div>
        </div>
    </div>
    <div class="sixteen wide column">
        <h3 class="ui header">Beschreibung</h3>
        {{book?.description}}
    </div>
</div>
<button (click)="showBookList()" class="ui red button">Zurück zur Buchliste</button>

// Ue03/bookshop-react/src/components/BookDetails.js
import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { baseUrl, getBookById } from "../api/bookApi";

export default function BookDetails(props) {

    const params = useParams();
    const navigate = useNavigate();

    const [book, setBook] = useState(undefined);

    useEffect(() => {
        getBookById(params.bookId).then(data => setBook(data.book));
    }, [params.bookId]);

    function onBackClick() {
        navigate('/books');
    }

    if (!book) {
        return <h1>Loading ...</h1>;
    }

    return (
        <div>
            <div className="ui grid">

                <div className="four wide column">
                    <img className="ui large image"
                        src={`${baseUrl}/${book.picture}`}
                        alt="book cover" />
                </div>

                <div className="eight wide column">
                    <h1 className="ui header">{book.title}</h1>
                    <h3 className="ui header">{book.author}</h3>
                    <div className="ui divider"></div>
                    <div className="ui grid">
                        <div className="four wide column">
                            <h4 className="ui header">Preis</h4>
                            {book.price}
                        </div>
                        <div className="four wide column">
                            <h4 className="ui header">Erschienen</h4>
                            {book.year}
                        </div>
                    </div>
                </div>
                <div className="sixteen wide column">
                    <h3 className="ui header">Beschreibung</h3>
                    {book.description}
                </div>
            </div>
            <button className="ui red button" onClick={onBackClick}>Zurück zur Buchliste</button>
        </div>
    );
}
