// Ue02/bookshop-client/src/app/book-details/book-details.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { ActivatedRoute, Router } from '@angular/router';
import { environment } from 'src/environments/environment';
import { Book } from '../shared/book';
import { BookStoreService } from '../shared/book-store.service';

@Component({
  selector: 'wea5-book-details',
  templateUrl: './book-details.component.html',
  styles: [
  ]
})
export class BookDetailsComponent implements OnInit {

  @Input() book: Book = new Book();
  @Output() showListEvent = new EventEmitter<any>();

  constructor(private route: ActivatedRoute,
    private bookStoreService: BookStoreService,
    private router: Router,
    private sanitizer: DomSanitizer) { }

  ngOnInit(): void {
    this.route.params.subscribe(params =>
      this.bookStoreService.getBookById(params['id'])
      .subscribe(res => this.book = res)
    );
  }

  showBookList() {
    // this.showListEvent.emit();
    this.router.navigateByUrl("/books");
  }

  imageUrl() {
    return this.sanitizer.bypassSecurityTrustResourceUrl(`${environment.images}/${this.book.picture}`)
  }

  addToShoppingCart() {
    const params = this.route.snapshot.params;
    let items: string[] = [];
    // get shopping cart from local storage
    let data = localStorage.getItem("WEA5.shoppingCart") || '[]';
    if(data != null) {
      items = JSON.parse(data);
    }
    items.push(params['id']);
    localStorage.setItem("WEA5.shoppingCart", JSON.stringify(items));
  }
}

<div class="ui grid" *ngIf="book">
    <div class="four wide column">
        <img class="ui large image" [src]="imageUrl()">
      </div>
  <div class="eight wide column">
    <h1 class="ui header">{{ book?.title }}</h1>
    <h3 class="ui header">{{ book?.author }}</h3>
    <div class="ui divider"></div>
    <div class="ui grid">
      <div class="four wide column">
    <h4 class="ui header">Preis</h4>
    {{ book?.price }}
    </div>
      <div class="four wide column">
    <h4 class="ui header">Erschienen</h4>
    {{ book?.year }}
    </div>
    </div>
    </div>
  <div class="sixteen wide column">
    <h3 class="ui header">Beschreibung</h3>
    {{ book?.description }}
    </div>
</div>
<button (click)="showBookList()" class="ui red button">Zurück zur Buchliste</button>
<a class="ui tiny yellow labeled icon button"
   *ngIf="book"
    [routerLink]="['/adminR', book?.id]">
  <i class="write icon"></i> Buch bearbeiten
</a>
<button type="button" (click)="addToShoppingCart()" class="ui red button">Kaufen</button>

// Ue03/bookshop-react/src/components/BookDetails.js
import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { baseUrl, getBookById } from "../api/bookApi";

export default function BookDetails(props) {

    const params = useParams();
    const navigate = useNavigate();

    const [book, setBook] = useState(undefined);

    useEffect(() => {
        getBookById(params.bookId).then(data => setBook(data.book));
    }, [params.bookId]);

    function onBackClick() {
        navigate('/books');
    }

    if (!book) {
        return <h1>Loading ...</h1>;
    }

    return (
        <div>
            <div className="ui grid">

                <div className="four wide column">
                    <img className="ui large image"
                        src={`${baseUrl}/${book.picture}`}
                        alt="book cover" />
                </div>

                <div className="eight wide column">
                    <h1 className="ui header">{book.title}</h1>
                    <h3 className="ui header">{book.author}</h3>
                    <div className="ui divider"></div>
                    <div className="ui grid">
                        <div className="four wide column">
                            <h4 className="ui header">Preis</h4>
                            {book.price}
                        </div>
                        <div className="four wide column">
                            <h4 className="ui header">Erschienen</h4>
                            {book.year}
                        </div>
                    </div>
                </div>
                <div className="sixteen wide column">
                    <h3 className="ui header">Beschreibung</h3>
                    {book.description}
                </div>
            </div>
            <button className="ui red button" onClick={onBackClick}>Zurück zur Buchliste</button>
        </div>
    );
}
