// Ue02/bookshop-client/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Book } from '../shared/book';

@Component({
  selector: 'wea5-home',
  template: `
    <div class="ui container two column grid">
      <div class="ui container column">
        <h1>Home</h1>
        <p>Willkommen im WEA5 BookShop.</p>
        <a routerLink="../books" class="ui red button">
          Buchliste ansehen
          <i class="right arrow icon"></i>
        </a>
      </div>
      <wea5-search (bookSelected)="bookSelected($event)" class="column"></wea5-search>
    </div>
  `,
  styles: [
  ]
})
export class HomeComponent implements OnInit {

  constructor(private router: Router, private route: ActivatedRoute) {}

  ngOnInit(): void {
  }

  bookSelected(book: Book) {
    this.router.navigate(['/books', book.id]);
  }
}

// Ue03/bookshop-react/src/components/Home.js
import { Link } from "react-router-dom";

export default function Home() {
    return (
        <div className="ui container">
            <h1>Home</h1>
            <p>Willkommen im WEA5 BookShop.</p>

            <Link className="ui red button" to="/books">
                Buchliste ansehen
                <i className="right arrow icon"></i>
            </Link>
        </div>
    );
}
